### ISSUE TITLE
研究md转换到html的机制

### ISSUE THREAD

**Issue by juniwang** [kaiyuanshe/kaiyuanshe#3]
研究可选方案：
- Github官方是否有比较好的工具
- 第三方工具
- 可考虑集成travis CI完成自动转换

除此之外，也可以考虑不用md格式

**Comment by LinuxSuRen** [comment]
什么场景需要做转换呢？

**Comment by juniwang** [comment]
将来的贡献方式（包括开源社内部成员）是写md，这个技术门槛低，也比较通用。除了开发组，让别的成员书写html（即便是富文本编辑器），都会比较有挑战性。

这个问题已经解决了：）
